# Copyright 2020-2023 Chris Croome
#
# This file is part of the Webarchitects ONLYOFFICE Ansible role.
#
# The Webarchitects ONLYOFFICE Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects ONLYOFFICE Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects ONLYOFFICE Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
variables:
  ANSIBLE_CALLBACK_RESULT_FORMAT: "yaml"
  ANSIBLE_DISPLAY_SKIPPED_HOSTS: "0"
  ANSIBLE_FORCE_COLOR: "1"
  ANSIBLE_REMOTE_TMP: "/tmp"
  ANSIBLE_SHELL_ALLOW_WORLD_READABLE_TEMP: "1"
  DEFAULT_MANAGED_STR: "Ansible managed"
  MOLECULE_VERBOSITY: "3"
  PY_COLORS: "1"
before_script:
  - apt install -yqqq tree
  - tree
  - whoami
  - pwd
  - which ansible
  - ansible --version
  - which yamllint
  - yamllint --version
  - which molecule
  - molecule --version
  - chmod 700 $(pwd)
  - mkdir -p molecule/default/roles
  - ansible-galaxy install -r molecule/default/requirements.yml -P molecule/default/roles --force
stages:
  - bookworm
  # - bullseye
  - jammy
bookworm:
  image: registry.git.coop/webarch/containers/images/bookworm:20231119
  stage: bookworm
  script:
    - molecule test
# The Bullseye test run OK but Molecule never completes
# https://github.com/ansible/molecule/discussions/4020
# bullseye:
#   image: registry.git.coop/webarch/containers/images/bullseye:20231119
#   stage: bullseye
#   script:
#     - molecule test
jammy:
  image: registry.git.coop/webarch/containers/images/jammy:20231119
  stage: jammy
  script:
    - molecule test
# vim: syntax=yaml
...
