---
all:
  children:
    onlyoffice_servers:
      hosts:
        onlyoffice.webarchitects.org.uk:
          ipv4_addr: 81.95.52.88
      vars:
        postgresql_user: onlyoffice
        postgresql_db: onlyoffice
...
