# Copyright 2020-2024 Chris Croome
#
# This file is part of the Webarchitects ONLYOFFICE Ansible role.
#
# The Webarchitects ONLYOFFICE Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects ONLYOFFICE Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects ONLYOFFICE Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Configure a .deb package
  block:

    - name: Debug onlyoffice_dcnf
      ansible.builtin.debug:
        var: onlyoffice_dcnf
        verbosity: 3

    - name: Debug onlyoffice_dcnf_existing
      ansible.builtin.debug:
        var: onlyoffice_dcnf_existing
        verbosity: 3

    - name: "Set a fact for an proposed regex and the existing debconf value for the debconf question {{ onlyoffice_dcnf.question }}"
      ansible.builtin.set_fact:
        onlyoffice_dcnf_current_value: >-
          {%- if onlyoffice_dcnf_existing is defined and onlyoffice_dcnf.vtype != 'password' -%}{{
          onlyoffice_dcnf_existing | community.general.json_query(onlyoffice_jpq_dcnf_question)
          }}{%- endif -%}
        onlyoffice_dcnf_proposed_value: "{{ onlyoffice_dcnf.value }}"
        onlyoffice_dcnf_proposed_value_regex: "^{{ onlyoffice_dcnf.value | ansible.builtin.regex_escape }}$"
      vars:
        onlyoffice_jpq_dcnf_question: "[?key=='{{ onlyoffice_dcnf.question }}'].value|[0]"

    - name: "Debug current value for the debconf question {{ onlyoffice_dcnf.question }}"
      ansible.builtin.debug:
        var: onlyoffice_dcnf_current_value
        verbosity: 1

    - name: "Debug current value type for the debconf question {{ onlyoffice_dcnf.question }}"
      ansible.builtin.debug:
        msg: "{{ onlyoffice_dcnf_current_value | ansible.builtin.type_debug }}"
        verbosity: 1

    - name: "Debug proposed value for the debconf question {{ onlyoffice_dcnf.question }}"
      ansible.builtin.debug:
        var: onlyoffice_dcnf_proposed_value
        verbosity: 1

    - name: "Debug proposed value type for the debconf question {{ onlyoffice_dcnf.question }}"
      ansible.builtin.debug:
        msg: "{{ onlyoffice_dcnf_proposed_value | ansible.builtin.type_debug }}"
        verbosity: 1

    - name: Check that the proposed value is a bool when the vtype is boolean
      ansible.builtin.assert:
        that:
          - onlyoffice_dcnf_proposed_value | type_debug == "bool"
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
        fail_msg: >-
          The variable onlyoffice_dcnf_proposed_value has the value {{ onlyoffice_dcnf_proposed_value }} and
          type of {{ onlyoffice_dcnf_proposed_value | ansible.builtin.type_debug }} when it should be a
          boolean because onlyoffice_dcnf.vtype has the value {{ onlyoffice_dcnf.vtype }}.
      when: onlyoffice_dcnf.vtype == "boolean"

    - name: Set debconf value in a block to catch errors
      block:

        - name: "Set debconf value for {{ onlyoffice_dcnf.question }}"
          ansible.builtin.debconf:
            name: "{{ onlyoffice_dcnf.name }}"
            question: "{{ onlyoffice_dcnf.question }}"
            value: >-
              {%- if onlyoffice_dcnf.vtype == "boolean" -%}{{-
              onlyoffice_dcnf_proposed_value | lower
              -}}{%- else -%}{{-
              onlyoffice_dcnf_proposed_value
              -}}{%- endif -%}
            vtype: >-
              {%- if onlyoffice_dcnf.vtype is ansible.builtin.regex('^[0-9]$') -%}string{%- else -%}{{-
              onlyoffice_dcnf.vtype
              -}}{%- endif -%}
          no_log: "{% if onlyoffice_dcnf.vtype == 'password' and ansible_verbosity == 0 %}true{% else %}false{% endif %}"
          changed_when:
            - onlyoffice_dcnf_current_value is not ansible.builtin.regex(onlyoffice_dcnf_proposed_value_regex)
            - onlyoffice_dcnf.vtype != "password"

      rescue:

        - name: Debug previous ansible.builtin.debconf task that failed
          ansible.builtin.fail:
            msg:
              - "name: {{ onlyoffice_dcnf.name }}"
              - "question: {{ onlyoffice_dcnf.question }}"
              - "value: {{ onlyoffice_debconf_value }}"
              - "vtype: {{ onlyoffice_dcnf.vtype }}"
          vars:
            onlyoffice_debconf_value: >-
              {%- if onlyoffice_dcnf.vtype == "boolean" -%}{{-
              onlyoffice_dcnf_proposed_value | lower
              -}}{%- else -%}{{-
              onlyoffice_dcnf_proposed_value
              -}}{%- endif -%}

      when: >-
        ( onlyoffice_dcnf_current_value is not defined ) or
        ( onlyoffice_dcnf_current_value is not ansible.builtin.regex(onlyoffice_dcnf_proposed_value_regex) )

  tags:
    - onlyoffice
...
