# Copyright 2020-2023 Chris Croome
#
# This file is part of the Webarchitects ONLYOFFICE Ansible role.
#
# The Webarchitects ONLYOFFICE Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects ONLYOFFICE Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects ONLYOFFICE Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Configure a .deb package
  block:

    - name: Check existing value when onlyoffice_dcnf_existing is defined
      block:

        - name: "Set a fact for an existing debconf value for the question {{ onlyoffice_dcnf.question }}"
          ansible.builtin.set_fact:
            onlyoffice_dcnf_current_value: "{{ onlyoffice_dcnf_existing | community.general.json_query(onlyoffice_jpq_dcnf_question) }}"
          vars:
            onlyoffice_jpq_dcnf_question: "[?key=='{{ onlyoffice_dcnf.question }}'].value|[0]"

        - name: Debug onlyoffice_dcnf_current_value
          ansible.builtin.debug:
            var: onlyoffice_dcnf_current_value
            verbosity: 2

      when:
        - onlyoffice_dcnf_existing is defined
        - onlyoffice_dcnf.vtype != "password"

    - name: "Set debconf value for {{ onlyoffice_dcnf.name }}"
      ansible.builtin.debconf:
        name: "{{ onlyoffice_dcnf.name }}"
        question: "{{ onlyoffice_dcnf.question }}"
        value: "{{ onlyoffice_dcnf.value }}"
        vtype: "{{ onlyoffice_dcnf.vtype }}"
      no_log: "{% if onlyoffice_dcnf.vtype == 'password' %}true{% else %}false{% endif %}"
      when: >-
        ( onlyoffice_dcnf_existing is not defined ) or
        ( ( office_dcnf_current_value is defined ) and
        ( onlyoffice_dcnf.value != onlyoffice_dcnf_current_value ) )

  tags:
    - onlyoffice
...
