---
- name: ONLYOFFICE JWT written and read
  block:

    - name: JWT secret present
      ansible.builtin.shell: pwgen -cns 32 1 > /root/.onlyoffice.jwt.secret
      args:
        creates: /root/.onlyoffice.jwt.secret

    - name: Slurp a base64 encoded version of the JWT secret
      ansible.builtin.slurp:
        src: /root/.onlyoffice.jwt.secret
      register: onlyoffice_jwt_secret_b64encoded

    - name: Decode the base64 encoded version of the file and set a variable
      ansible.builtin.set_fact:
        onlyoffice_jwt_secret: "{{ onlyoffice_jwt_secret_b64encoded['content'] | b64decode | trim }}"

  tags:
    - onlyoffice
...
