# Copyright 2020-2023 Chris Croome
#
# This file is part of the Webarchitects ONLYOFFICE Ansible role.
#
# The Webarchitects ONLYOFFICE Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects ONLYOFFICE Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects ONLYOFFICE Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Skip the tasks in this role as onlyoffice is false
  ansible.builtin.debug:
    msg: "The onlyoffice variable need to be true for the tasks in this role to run."
  when: not onlyoffice | bool
  tags:
    - onlyoffice
    - onlyoffice_apt

- name: Configure ONLYOFFICE apt repo
  block:

    - name: Include apt role local fact tasks if variables are not defined
      ansible.builtin.include_role:
        name: apt
        tasks_from: local_facts.yml
      when: >-
        ( ansible_local.dpkg.arch is not defined ) or
        ( ansible_local.gpg.version is not defined ) or
        ( ansible_local.bash.path is not defined )

    - name: Include ONLYOFFICE apt repo config and install fonts and other package tasks
      ansible.builtin.include_tasks: apt.yml

  when: onlyoffice | bool
  tags:
    - onlyoffice
    - onlyoffice_apt

- name: ONLYOFFICE Document Server
  block:

    - name: Validate ONLYOFFICE variables
      ansible.builtin.include_tasks: verify.yml
      when: onlyoffice_verify | bool

    - name: Include check tasks
      ansible.builtin.include_tasks: checks.yml

    - name: Include read and set variable tasks
      ansible.builtin.include_tasks: vars.yml

    - name: Skipping debconf ONLYOFFICE tasks as debconf-utils is not present
      ansible.builtin.debug:
        msg: The debconf-utils packages is required for the configuration of the ONLYOFFICE DocumentServer prior to installing it.
      when: ( "debconf-utils" not in ansible_local.dpkg.installed )

    - name: ONLYOFFICE Document Server Install tasks
      block:

        - name: Include debconf ONLYOFFICE tasks
          ansible.builtin.include_tasks: debconf.yml
          loop: "{{ onlyoffice_debconf }}"
          loop_control:
            loop_var: onlyoffice_dcnf
            label: "{{ onlyoffice_dcnf.question }}"

        - name: Include install ONLYOFFICE tasks
          ansible.builtin.include_tasks: install.yml

        - name: Include Munin tasks
          ansible.builtin.include_tasks: munin.yml

        - name: Include Nginx tasks
          ansible.builtin.include_tasks: nginx.yml

      when: ( "debconf-utils" in ansible_local.dpkg.installed )

    - name: Ensure that the ONLYOFFICE ds-docservice is enabled and started
      ansible.builtin.systemd_service:
        service: ds-docservice
        enabled: true
        state: started
      notify:
        - Restart docservice

  when: onlyoffice | bool
  tags:
    - onlyoffice
...
