---
- name: Apt package facts checked
  package_facts:
    manager: apt
  tags:
    - onlyoffice

# Should these always be run together with a dpkg-reconfigure onlyoffice-documentserver?
- name: Install onlyoffice-documentserver if it isn't installed
  block:

    - name: Enable ONLYOFFICE apt repo
      include_tasks: apt.yml

    - name: Read and set variables
      include_tasks: vars.yml

    - name: Debconf for ONLYOFFICE
      include_tasks: debconf.yml

    - name: Install ONLYOFFICE
      include_tasks: install.yml

  when: ( "onlyoffice-documentserver" not in ansible_facts.packages )
  tags:
    - onlyoffice

# https://helpcenter.onlyoffice.com/server/linux/document/switch-to-https.aspx
- name: Nginx configuration in place
  template:
    src: ds.conf.j2
    dest: /etc/onlyoffice/documentserver/nginx/ds.conf
  tags:
    - onlyoffice

- name: Ngnix restarted
  service:
    name: nginx
    state: restarted
  tags:
    - onlyoffice
...
