---
- name: ONLYOFFICE Document Server
  block:

    - name: Include apt role local fact tasks if variables are not defined
      ansible.builtin.include_role:
        name: apt
        tasks_from: local_facts.yml
      when: >-
        ( ansible_local.dpkg.arch is not defined ) or
        ( ansible_local.gpg.version is not defined ) or
        ( ansible_local.bash.path is not defined )

    - name: Include ONLYOFFICE apt repo config and install fonts and other package tasks
      ansible.builtin.include_tasks: apt.yml

    - name: Include read and set variable tasks
      ansible.builtin.include_tasks: vars.yml

    - name: Include debconf ONLYOFFICE tasks
      ansible.builtin.include_tasks: debconf.yml

    - name: Include install ONLYOFFICE tasks
      ansible.builtin.include_tasks: install.yml

    - name: Include Nginx tasks
      ansible.builtin.include_tasks: nginx.yml
      when: (onlyoffice_webserver is defined) and (onlyoffice_webserver == "nginx")
      tags:
        - nginx

  when: onlyoffice | bool
  tags:
    - onlyoffice
...
