---
- name: Apt package facts checked
  package_facts:
    manager: apt
  tags:
    - onlyoffice

# Should these always be run together with a dpkg-reconfigure onlyoffice-documentserver?
- name: Install onlyoffice-documentserver if it isn't installed
  block:

    - name: Enable ONLYOFFICE apt repo
      include_tasks: apt.yml

    - name: Read and set variables
      include_tasks: vars.yml

    - name: Debconf for ONLYOFFICE
      include_tasks: debconf.yml

    - name: Install ONLYOFFICE
      include_tasks: install.yml

  when: ( "onlyoffice-documentserver" not in ansible_facts.packages )
  tags:
    - onlyoffice

- name: Include Nginx tasks
  include_tasks: nginx.yml
  when: ( onlyoffice_webserver is defined ) and ( onlyoffice_webserver == "nginx" )
  tags:
    - onlyoffice
    - nginx
...
