# Copyright 2020-2023 Chris Croome
#
# This file is part of the Webarchitects ONLYOFFICE Ansible role.
#
# The Webarchitects ONLYOFFICE Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects ONLYOFFICE Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects ONLYOFFICE Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Configure ONLYOFFICE Munin plugin
  block:

    - name: Munin plugin directory present
      ansible.builtin.file:
        path: /usr/local/share/munin/plugins
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: State /usr/local/share/munin/plugins
      ansible.builtin.stat:
        path: /usr/local/share/munin/plugins
      register: onlyoffice_munin_usr_local_share_munin_plugins_path

    - name: ONLYOFFICE Munin present
      ansible.builtin.template:
        src: onlyoffice.sh.j2
        dest: /usr/local/share/munin/plugins/onlyoffice
        mode: "0755"
        owner: root
        group: root
      when: onlyoffice_munin_usr_local_share_munin_plugins_path.stat.exists | bool

    - name: State /etc/munin/plugins
      ansible.builtin.stat:
        path: /etc/munin/plugins
      register: onlyoffice_munin_etc_plugins_path

    - name: ONLYOFFICE Munin symlink in place
      ansible.builtin.file:
        src: /usr/local/share/munin/plugins/onlyoffice
        dest: /etc/munin/plugins/onlyoffice
        state: link
        follow: false
        mode: "0777"
        owner: root
        group: root
      when: onlyoffice_munin_etc_plugins_path.stat.exists | bool

  tags:
    - onlyoffice
...
