# Copyright 2020-2023 Chris Croome
#
# This file is part of the Webarchitects ONLYOFFICE Ansible role.
#
# The Webarchitects ONLYOFFICE Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects ONLYOFFICE Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects ONLYOFFICE Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: ONLYOFFICE Document Server Nginx configuration
  block:

    - name: Include JSON Web Token tasks
      ansible.builtin.include_tasks: jwt.yml

    - name: Ensure that the JWT is defined
      ansible.builtin.assert:
        that:
          - onlyoffice_jwt_secret is defined
          - onlyoffice_jwt_secret | length > 0

    # https://helpcenter.onlyoffice.com/server/linux/document/switch-to-https.aspx
    - name: Nginx configuration in place
      ansible.builtin.template:
        src: ds.conf.j2
        dest: /etc/onlyoffice/documentserver/nginx/ds.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart nginx

    - name: Robots.txt in place
      ansible.builtin.template:
        src: robots.txt.j2
        dest: /usr/share/nginx/html/robots.txt
        owner: root
        group: root
        mode: 0644

    - name: Nginx default and localhost sites disabled
      ansible.builtin.file:
        path: "/etc/nginx/sites-enabled/{{ file }}"
        state: absent
      loop:
        - default
        - default.conf
        - localhost.conf
      loop_control:
        loop_var: file
      notify: Restart nginx

    - name: Nginx configtest
      ansible.builtin.command: service nginx configtest
      check_mode: false
      changed_when: false
      notify: Restart nginx

  tags:
    - onlyoffice
...
