# Copyright 2020-2023 Chris Croome
#
# This file is part of the Webarchitects ONLYOFFICE Ansible role.
#
# The Webarchitects ONLYOFFICE Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects ONLYOFFICE Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects ONLYOFFICE Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: ONLYOFFICE Document Server Nginx configuration
  block:

    - name: Include JSON Web Token tasks
      ansible.builtin.include_tasks: jwt.yml

    - name: Ensure that the ONLYOFFICE storage.fs.secretstring is defined
      ansible.builtin.assert:
        that:
          - onlyoffice_local_fs_secretstring is defined
          - onlyoffice_local_fs_secretstring | length > 0
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: Read package facts
      ansible.builtin.package_facts:
        manager: apt

    - name: Set a fact for the ONLYOFFICE apt package version
      ansible.builtin.set_fact:
        onlyoffice_docserver_apt_version: "{{ ansible_facts.packages['onlyoffice-documentserver'] | community.general.json_query('[0].version') }}"

    - name: Debug onlyoffice_docserver_apt_version
      ansible.builtin.debug:
        var: onlyoffice_docserver_apt_version
        verbosity: 1

    - name: Ensure that the ONLYOFFICE apt package version is defined and matches the required version
      ansible.builtin.assert:
        that:
          - onlyoffice_docserver_apt_version is defined
          - onlyoffice_docserver_apt_version is ansible.builtin.version('7.4.1-36', '>=')
          - onlyoffice_docserver_apt_version == onlyoffice_docserver_version
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
      when: not ansible_check_mode | bool

    - name: Check if the original /etc/onlyoffice/documentserver/nginx/ds.conf exists
      ansible.builtin.stat:
        path: /etc/onlyoffice/documentserver/nginx/ds.conf
      register: onlyoffice_nginx_ds_conf_original

    - name: Check if a backup of the original /etc/onlyoffice/documentserver/nginx/ds.conf exists
      ansible.builtin.stat:
        path: /etc/onlyoffice/documentserver/nginx/ds.conf.ansible.backup
      register: onlyoffice_nginx_ds_conf_backup

    - name: Copy the original /etc/onlyoffice/documentserver/nginx/ds.conf
      ansible.builtin.copy:
        src: /etc/onlyoffice/documentserver/nginx/ds.conf
        dest: /etc/onlyoffice/documentserver/nginx/ds.conf.ansible.backup
        remote_src: true
        owner: root
        group: root
        mode: "0644"
      when:
        - onlyoffice_nginx_ds_conf_original.stat.exists | bool
        - not onlyoffice_nginx_ds_conf_backup.stat.exists | bool

    # https://helpcenter.onlyoffice.com/server/linux/document/switch-to-https.aspx
    - name: Nginx /etc/onlyoffice/documentserver/nginx/ds.conf configuration in place
      ansible.builtin.template:
        src: ds.conf.j2
        dest: /etc/onlyoffice/documentserver/nginx/ds.conf
        owner: root
        group: root
        mode: "0644"
        backup: true
      notify: Restart nginx

    - name: Check if the original /etc/onlyoffice/documentserver/nginx/includes/ds-docservice.conf exists
      ansible.builtin.stat:
        path: /etc/onlyoffice/documentserver/nginx/includes/ds-docservice.conf
      register: onlyoffice_nginx_ds_docservice_conf_original

    - name: Check if a backup of the original /etc/onlyoffice/documentserver/nginx/includes/ds-docservice.conf exists
      ansible.builtin.stat:
        path: /etc/onlyoffice/documentserver/nginx/includes/ds-docservice.conf.ansible.backup
      register: onlyoffice_nginx_ds_docservice_conf_backup

    - name: Copy the original /etc/onlyoffice/documentserver/nginx/includes/ds-docservice.conf
      ansible.builtin.copy:
        src: /etc/onlyoffice/documentserver/nginx/includes/ds-docservice.conf
        dest: /etc/onlyoffice/documentserver/nginx/includes/ds-docservice.conf.ansible.backup
        remote_src: true
        owner: root
        group: root
        mode: "0644"
      when:
        - onlyoffice_nginx_ds_docservice_conf_original.stat.exists | bool
        - not onlyoffice_nginx_ds_docservice_conf_backup.stat.exists | bool

    - name: Nginx /etc/onlyoffice/documentserver/nginx/includes/ds-docservice.conf configuration in place
      ansible.builtin.template:
        src: ds-docservice.conf.j2
        dest: /etc/onlyoffice/documentserver/nginx/includes/ds-docservice.conf
        owner: root
        group: root
        mode: "0644"
        backup: true
      notify: Restart nginx

    - name: Template http-common.conf when the docserver port is not 8000
      block:

        - name: Check if the original /etc/onlyoffice/documentserver/nginx/includes/http-common.conf exists
          ansible.builtin.stat:
            path: /etc/onlyoffice/documentserver/nginx/includes/http-common.conf
          register: onlyoffice_nginx_http_common_conf_original

        - name: Check if a backup of the original /etc/onlyoffice/documentserver/nginx/includes/http-common.conf exists
          ansible.builtin.stat:
            path: /etc/onlyoffice/documentserver/nginx/includes/http-common.conf.ansible.backup
          register: onlyoffice_nginx_http_common_conf_backup

        - name: Copy the original /etc/onlyoffice/documentserver/nginx/includes/http-common.conf
          ansible.builtin.copy:
            src: /etc/onlyoffice/documentserver/nginx/includes/http-common.conf
            dest: /etc/onlyoffice/documentserver/nginx/includes/http-common.conf.ansible.backup
            remote_src: true
            owner: root
            group: root
            mode: "0644"
          when:
            - onlyoffice_nginx_http_common_conf_original.stat.exists | bool
            - not onlyoffice_nginx_http_common_conf_backup.stat.exists | bool

        - name: Nginx /etc/onlyoffice/documentserver/nginx/includes/http-common.conf configuration in place
          ansible.builtin.template:
            src: http-common.conf.j2
            dest: /etc/onlyoffice/documentserver/nginx/includes/http-common.conf
            owner: root
            group: root
            mode: "0644"
            backup: true
          notify: Restart nginx

      when:
        - onlyoffice_jpq_docservice_port is defined
        - onlyoffice_jpq_docservice_port != "8000"

    - name: Robots.txt in place
      ansible.builtin.template:
        src: robots.txt.j2
        dest: /usr/share/nginx/html/robots.txt
        owner: root
        group: root
        mode: "0644"

    - name: Nginx default and localhost sites disabled
      ansible.builtin.file:
        path: "/etc/nginx/sites-enabled/{{ file }}"
        state: absent
      loop:
        - default
        - default.conf
        - localhost.conf
      loop_control:
        loop_var: file
      notify: Restart nginx

    - name: Nginx configtest  # noqa: command-instead-of-module
      ansible.builtin.command: service nginx configtest
      check_mode: false
      changed_when: false
      notify: Restart nginx

  tags:
    - onlyoffice
...
