# Copyright 2020-2024 Chris Croome
#
# This file is part of the Webarchitects ONLYOFFICE Ansible role.
#
# The Webarchitects ONLYOFFICE Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects ONLYOFFICE Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects ONLYOFFICE Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: ONLYOFFICE Document Server Nginx configuration
  block:

    - name: Include JSON Web Token tasks
      ansible.builtin.include_tasks: jwt.yml

    - name: Ensure that the ONLYOFFICE storage.fs.secretstring is defined
      ansible.builtin.assert:
        that:
          - onlyoffice_local_fs_secretstring is defined
          - onlyoffice_local_fs_secretstring | length > 0
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: Read package facts
      ansible.builtin.package_facts:
        manager: apt

    - name: Set a fact for the ONLYOFFICE apt package version
      ansible.builtin.set_fact:
        onlyoffice_docserver_apt_version: "{{ ansible_facts.packages['onlyoffice-documentserver'] | community.general.json_query('[0].version') }}"

    - name: Debug onlyoffice_docserver_apt_version
      ansible.builtin.debug:
        var: onlyoffice_docserver_apt_version
        verbosity: 1

    - name: Ensure that the ONLYOFFICE apt package version is defined and matches the required version
      ansible.builtin.assert:
        that:
          - onlyoffice_docserver_apt_version is defined
          - onlyoffice_docserver_apt_version is ansible.builtin.version('7.4.1-36', '>=')
          - onlyoffice_docserver_apt_version == onlyoffice_docserver_version
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
      when: not ansible_check_mode | bool

    - name: Check if the original /etc/onlyoffice/documentserver/nginx/ds.conf exists
      ansible.builtin.stat:
        path: /etc/onlyoffice/documentserver/nginx/ds.conf
      register: onlyoffice_nginx_ds_conf_original

    - name: Check if a backup of the original /etc/onlyoffice/documentserver/nginx/ds.conf exists
      ansible.builtin.stat:
        path: /etc/onlyoffice/documentserver/nginx/ds.conf.ansible.backup
      register: onlyoffice_nginx_ds_conf_backup

    - name: Copy the original /etc/onlyoffice/documentserver/nginx/ds.conf
      ansible.builtin.copy:
        src: /etc/onlyoffice/documentserver/nginx/ds.conf
        dest: /etc/onlyoffice/documentserver/nginx/ds.conf.ansible.backup
        remote_src: true
        owner: root
        group: root
        mode: "0644"
      when:
        - onlyoffice_nginx_ds_conf_original.stat.exists | bool
        - not onlyoffice_nginx_ds_conf_backup.stat.exists | bool

    - name: Ensure that /etc/nginx/conf.d/ds.conf is a symlink to /etc/onlyoffice/documentserver/nginx/ds.conf
      ansible.builtin.file:
        src: "/etc/onlyoffice/documentserver/nginx/ds.conf"
        dest: "/etc/nginx/conf.d/ds.conf"
        state: link
        follow: false
        mode: "0777"
        owner: root
        group: root
      when: onlyoffice_nginx_ds_conf_original.stat.exists | bool
      notify: Restart nginx

    # https://helpcenter.onlyoffice.com/server/linux/document/switch-to-https.aspx
    - name: Nginx /etc/onlyoffice/documentserver/nginx/ds.conf configuration in place
      ansible.builtin.template:
        src: ds.conf.j2
        dest: /etc/onlyoffice/documentserver/nginx/ds.conf
        owner: root
        group: root
        mode: "0644"
        backup: true
      notify: Restart nginx

    - name: Nginx HTTP to HTTPS redirect configuration in place
      ansible.builtin.template:
        src: onlyoffice_redirect.conf.j2
        dest: /etc/nginx/sites-available/onlyoffice_redirect.conf
        owner: root
        group: root
        mode: "0644"
        backup: true
      notify: Restart nginx

    - name: Check if the Nginx HTTP to HTTPS redirect configuration is present
      ansible.builtin.stat:
        path: /etc/nginx/sites-available/onlyoffice_redirect.conf
      register: onlyoffice_nginx_https_redirect_config

    - name: Nginx HTTP to HTTPS redirect configuration enabled
      ansible.builtin.file:
        src: /etc/nginx/sites-available/onlyoffice_redirect.conf
        dest: /etc/nginx/sites-enabled/onlyoffice_redirect.conf
        state: link
        follow: false
        mode: "0777"
        owner: root
        group: root
      when:
        - onlyoffice_ssl is defined
        - onlyoffice_ssl | bool
        - onlyoffice_nginx_https_redirect_config.stat.exists is defined
        - onlyoffice_nginx_https_redirect_config.stat.exists | bool
      notify: Restart nginx

    - name: Nginx HTTP to HTTPS redirect configuration disabled
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/onlyoffice_redirect.conf
        state: absent
      when: not onlyoffice_ssl | bool
      notify: Restart nginx

    - name: Nginx localhost for ONLYOFFICE info
      block:

        - name: Nginx localhost info configuration in place
          ansible.builtin.template:
            src: onlyoffice_localhost.conf.j2
            dest: /etc/nginx/sites-available/onlyoffice_localhost.conf
            owner: root
            group: root
            mode: "0644"
            backup: true
          notify: Restart nginx

        - name: Check if the Nginx localhost configuration is present
          ansible.builtin.stat:
            path: /etc/nginx/sites-available/onlyoffice_localhost.conf
          register: onlyoffice_nginx_https_localhost_config

        - name: Nginx HTTP to HTTPS localhost configuration enabled
          ansible.builtin.file:
            src: /etc/nginx/sites-available/onlyoffice_localhost.conf
            dest: /etc/nginx/sites-enabled/onlyoffice_localhost.conf
            state: link
            follow: false
            mode: "0777"
            owner: root
            group: root
          when:
            - onlyoffice_nginx_https_localhost_config.stat.exists is defined
            - onlyoffice_nginx_https_localhost_config.stat.exists | bool
          notify: Restart nginx

      when: onlyoffice_nginx_localhost | bool

    - name: Template http-common.conf when the docserver port is not 8000 or the docserver host is not localhost
      block:

        - name: Check if the original /etc/onlyoffice/documentserver/nginx/includes/http-common.conf exists
          ansible.builtin.stat:
            path: /etc/onlyoffice/documentserver/nginx/includes/http-common.conf
          register: onlyoffice_nginx_http_common_conf_original

        - name: Check if a backup of the original /etc/onlyoffice/documentserver/nginx/includes/http-common.conf exists
          ansible.builtin.stat:
            path: /etc/onlyoffice/documentserver/nginx/includes/http-common.conf.ansible.backup
          register: onlyoffice_nginx_http_common_conf_backup

        - name: Copy the original /etc/onlyoffice/documentserver/nginx/includes/http-common.conf
          ansible.builtin.copy:
            src: /etc/onlyoffice/documentserver/nginx/includes/http-common.conf
            dest: /etc/onlyoffice/documentserver/nginx/includes/http-common.conf.ansible.backup
            remote_src: true
            owner: root
            group: root
            mode: "0644"
          when:
            - onlyoffice_nginx_http_common_conf_original.stat.exists | bool
            - not onlyoffice_nginx_http_common_conf_backup.stat.exists | bool

        - name: Nginx /etc/onlyoffice/documentserver/nginx/includes/http-common.conf configuration in place
          ansible.builtin.template:
            src: http-common.conf.j2
            dest: /etc/onlyoffice/documentserver/nginx/includes/http-common.conf
            owner: root
            group: root
            mode: "0644"
            backup: true
          notify: Restart nginx

      when: >-
        ( ( onlyoffice_ds_port is defined ) and ( onlyoffice_ds_port != "8000" ) ) or
        ( ( onlyoffice_ds_host is defined ) and ( onlyoffice_ds_host != "localhost" ) )

    - name: Robots.txt in place
      ansible.builtin.template:
        src: robots.txt.j2
        dest: /usr/share/nginx/html/robots.txt
        owner: root
        group: root
        mode: "0644"

    - name: Nginx default and localhost sites disabled
      ansible.builtin.file:
        path: "/etc/nginx/sites-enabled/{{ onlyoffice_nginx_symlink }}"
        state: absent
      loop: "{{ onlyoffice_nginx_sites_disabled }}"
      loop_control:
        loop_var: onlyoffice_nginx_symlink
      when:
        - onlyoffice_nginx_sites_disabled is defined
        - onlyoffice_nginx_sites_disabled != []
      notify: Restart nginx

    - name: Nginx configtest  # noqa: command-instead-of-module
      ansible.builtin.command: service nginx configtest
      check_mode: false
      changed_when: false
      notify: Restart nginx

  tags:
    - onlyoffice
...
