# Copyright 2020-2024 Chris Croome
#
# This file is part of the Webarchitects ONLYOFFICE Ansible role.
#
# The Webarchitects ONLYOFFICE Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects ONLYOFFICE Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects ONLYOFFICE Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
argument_specs:
  main:
    author: Chris Croome
    description: ONLYOFFICE Document Server Ansible role
    short_description: The main entry point for the ONLYOFFICE role.
    options:
      onlyoffice:
        type: bool
        required: true
        description: Run the tasks in this role.
      onlyoffice_db_type:
        type: str
        required: true
        description: The database server engine.
        choices:
          - mariadb
          - postgres
      onlyoffice_db_port:
        type: str
        required: true
        description: The database port, quoted.
      onlyoffice_docservice_port:
        type: str
        required: true
        description: The ONLYOFFICE DocumentServer backend port, quoted.
      onlyoffice_ds_port:
        type: str
        required: true
        description: The ONLYOFFICE DocumentServer Nginx port, quoted.
      onlyoffice_debconf:
        type: list
        elements: dict
        required: true
        description: ONLYOFFICE debconf settings.
        options:
          name:
            type: str
            required: true
            description: Name of package to configure.
          question:
            type: str
            required: true
            description: A debconf configuration setting.
          value:
            type: str
            required: true
            description: Value to set the configuration to.
          vtype:
            type: str
            required: true
            description: The type of the value supplied.
            choices:
              - boolean
              - error
              - multiselect
              - note
              - password
              - seen
              - select
              - string
              - text
              - title
      onlyoffice_db_pwd:
        type: str
        required: true
        description: ONLYOFFICE database password.
      onlyoffice_dcnf:
        type: dict
        required: false
        description: Internal debconf loop variable.
        options:
          value:
            type: str
            required: true
            description: Value for the debconf question.
      onlyoffice_docserver_version:
        type: str
        required: true
        description: The version of the onlyoffice-documentserver package to be pinned.
      onlyoffice_local:
        type: dict
        required: true
        description: The ONLYOFFICE local.json configuration.
        options:
          rabbitmq:
            type: dict
            required: true
            description: The ONLYOFFICE local.json RabbitMQ configuration.
            options:
              url:
                type: str
                required: true
                description: The ONLYOFFICE local.json RabbitMQ configuration URL.
          server:
            type: dict
            required: true
            description: The ONLYOFFICE local.json server configuration.
            options:
              port:
                type: str
                required: true
                description: The ONLYOFFICE server port number, quoted to ensure it is a string.
          services:
            type: dict
            required: true
            description: The ONLYOFFICE local.json services configuration.
            options:
              CoAuthoring:
                type: dict
                required: true
                description: The ONLYOFFICE local.json CoAuthoring configuration.
                options:
                  secret:
                    type: dict
                    required: true
                    description: The ONLYOFFICE local.json JWT secrets.
                    options:
                      inbox:
                        type: dict
                        required: true
                        description: The ONLYOFFICE local.json inbox configuration.
                        options:
                          string:
                            type: str
                            required: true
                            description: The ONLYOFFICE local.json inbox JWT secret.
                      outbox:
                        type: dict
                        required: true
                        description: The ONLYOFFICE local.json outbox configuration.
                        options:
                          string:
                            type: str
                            required: true
                            description: The ONLYOFFICE local.json outbox JWT secret.
                      session:
                        type: dict
                        required: true
                        description: The ONLYOFFICE local.json session configuration.
                        options:
                          string:
                            type: str
                            required: true
                            description: The ONLYOFFICE local.json session JWT secret.
                  sql:
                    type: dict
                    required: true
                    description: The ONLYOFFICE local.json database configuration.
                    options:
                      type:
                        type: str
                        required: true
                        description: The ONLYOFFICE local.json database type.
                        choices:
                          - mariadb
                          - postgres
                      dbHost:
                        type: str
                        required: true
                        description: The ONLYOFFICE local.json database host.
                      dbPort:
                        type: str
                        required: true
                        description: The ONLYOFFICE local.json database port.
                      dbName:
                        type: str
                        required: true
                        description: The ONLYOFFICE local.json database name.
                      dbUser:
                        type: str
                        required: true
                        description: The ONLYOFFICE local.json database user.
                      dbPass:
                        type: str
                        required: true
                        description: The ONLYOFFICE local.json database password.
                  token:
                    type: dict
                    required: true
                    description: The ONLYOFFICE local.json token configuration.
                    options:
                      enable:
                        type: dict
                        required: true
                        description: The ONLYOFFICE local.json tokens to enable.
                        options:
                          browser:
                            type: bool
                            required: true
                            description: Enable the ONLYOFFICE local.json browser token.
                          request:
                            type: dict
                            required: true
                            description: The ONLYOFFICE local.json request tokens to enable.
                            options:
                              inbox:
                                type: bool
                                required: true
                                description: Enable the ONLYOFFICE local.json inbox token.
                              outbox:
                                type: bool
                                required: true
                                description: Enable the ONLYOFFICE local.json outbox token.
                      inbox:
                        type: dict
                        required: true
                        description: The ONLYOFFICE local.json inbox header configuration.
                        options:
                          header:
                            type: str
                            required: true
                            description: The ONLYOFFICE local.json inbox HTTP header.
                      outbox:
                        type: dict
                        required: true
                        description: The ONLYOFFICE local.json outbox header configuration.
                        options:
                          header:
                            type: str
                            required: true
                            description: The ONLYOFFICE local.json outbox HTTP header.
          storage:
            type: dict
            required: true
            description: The ONLYOFFICE local.json storage configuration.
            options:
              fs:
                type: dict
                required: true
                description: The ONLYOFFICE local.json filesystem storage configuration.
                options:
                  secretString:
                    type: str
                    required: true
                    description: The ONLYOFFICE local.json filesystem storage configuration secret string.
          # https://api.onlyoffice.com/editors/wopi/
          wopi:
            type: dict
            required: false
            description: Optional ONLYOFFICE WOPI configuration.
            options:
              enable:
                type: bool
                required: true
                description: Defines if ONLYOFFICE WOPI is enabled or not. The default value is false.
              exponent:
                type: int
                required: false
                description: ONLYOFFICE WOPI exponent.
              exponentOld:
                type: int
                required: false
                description: ONLYOFFICE WOPI exponentOld.
              modulus:
                type: str
                required: false
                description: ONLYOFFICE WOPI modulus.
              modulusOld:
                type: str
                required: false
                description: ONLYOFFICE WOPI modulusOld.
              privateKey:
                type: str
                required: false
                description: ONLYOFFICE WOPI privateKey.
              privateKeyOld:
                type: str
                required: false
                description: ONLYOFFICE WOPI privateKeyOld.
              publicKey:
                type: str
                required: false
                description: ONLYOFFICE WOPI publicKey.
              publicKeyOld:
                type: str
                required: false
                description: ONLYOFFICE WOPI publicKeyOld.
      onlyoffice_mariadb_priv:
        type: list
        elements: str
        required: true
        description: A list of MariaDB privs.
      onlyoffice_mariadb_socket:
        type: str
        required: false
        description: Path to the MariaDB socket.
      onlyoffice_nginx_localhost:
        type: bool
        required: true
        description: Listen for local connections to the ONLYOFFICE info URL.
      onlyoffice_nginx_localhost_domain:
        type: str
        required: true
        description: Domain name / IP address for local connections to the ONLYOFFICE info URL.
      onlyoffice_nginx_localhost_port:
        type: int
        required: true
        description: Port for local connections to the ONLYOFFICE info URL.
      onlyoffice_nginx_sites_disabled:
        type: list
        elements: str
        required: false
        description: A list of Nginx sites to disable, which are symlinks to delete in /etc/nginx/sites-enabled.
      onlyoffice_nginx_sites_enabled:
        type: list
        elements: str
        required: false
        description: A list of Nginx sites to enable, which are symlinks to add in /etc/nginx/sites-enabled.
      onlyoffice_pkg:
        type: list
        elements: str
        required: true
        description: A list of required .deb packages.
      onlyoffice_rabbitmq_host:
        type: str
        required: true
        description: The RabbitMQ host.
      onlyoffice_rabbitmq_pwd:
        type: str
        required: false
        description: RabbitMQ password for ONLYOFFICE, internally set using the RabbitMQ role.
      onlyoffice_ssl:
        type: bool
        required: true
        description: Nginx TLS enabled.
      onlyoffice_ssl_certificate:
        type: str
        required: true
        description: Path to the TLS cert.
      onlyoffice_ssl_certificate_key:
        type: str
        required: true
        description: Path to the TLS key.
      onlyoffice_verify:
        type: bool
        required: true
        description: Use ansible.builtin.validate_argument_spec module to validate role argument specs.
      onlyoffice_wopi:
        type: str
        required: true
        description: Fail if local.json wopi config is not defined by this role or ignore it.
        choices:
          - fail
          - ignore
...
