---
- name: Nginx restarted
  ansible.builtin.service:
    name: nginx
    state: restarted
  listen: Restart nginx

- name: ONLYOFFICE docservice restarted
  community.general.supervisorctl:
    name: ds:docservice
    state: restarted
  listen: Restart docservice

- name: ONLYOFFICE converter restarted
  community.general.supervisorctl:
    name: ds:converter
    state: restarted
  listen: Restart converter
...
