# Copyright 2021-2023 Chris Croome
#
# This file is part of the Webarchitects ONLYOFFICE Ansible role.
#
# The Webarchitects ONLYOFFICE Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects ONLYOFFICE Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects ONLYOFFICE Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Run as root
  # become: true
  connection: local
  gather_facts: true
  hosts:
    - localhost
  tasks:

    - name: Debug ansible_facts.effective_user_id
      ansible.builtin.debug:
        var: ansible_facts.effective_user_id

    - name: Debug ansible_facts.user_id
      ansible.builtin.debug:
        var: ansible_facts.user_id

    - name: Debug ansible_facts.user_dir
      ansible.builtin.debug:
        var: ansible_facts.user_dir

    - name: Run hostname -f
      ansible.builtin.command: hostname -f
      check_mode: false
      changed_when: false
      register: molecule_hostname_f

    - name: Set a fact for the hostname
      ansible.builtin.set_fact:
        molecule_hostname: "{{ molecule_hostname_f.stdout }}"

    - name: Include /etc/hosts role as root
      ansible.builtin.include_role:
        name: etchosts
      vars:  # noqa var-naming[no-role-prefix]
        etchosts: true
        etchosts_file:
          - ip: 127.0.0.1
            hostname:
              - localhost
          - ip: "{{ ansible_facts.default_ipv4.address }}"
            hostname:
              - "{{ molecule_hostname }}"
          - ip: ::1
            hostname:
              - ip6-localhost
              - ip6-loopback
          - ip: fe00::0
            hostname:
              - ip6-localnet
          - ip: ff00::0
            hostname:
              - ip6-mcastprefix
          - ip: ff02::1
            hostname:
              - ip6-allnodes
          - ip: ff02::2
            hostname:
              - ip6-allrouters
          - ip: ff02::3
            hostname:
              - ip6-allhosts
        etchosts_hostname_strategy: systemd
        etchosts_unsafe_writes: true

    - name: Include the Nginx role
      ansible.builtin.include_role:
        name: nginx
      vars:  # noqa var-naming[no-role-prefix]
        nginx: true
        nginx_default_server_port: 81
        nginx_sites_disabled:
          - default
          - default.conf
        nginx_sites_enabled:
          - localhost.conf
        nginx_ssl: false

    - name: Include the MariaDB role
      ansible.builtin.include_role:
        name: mariadb
      vars:  # noqa var-naming[no-role-prefix]
        mariadb: true
        mariadb_systemd_units:
          - name: mariadb
            state: enabled
            files:
              - path: /etc/systemd/system/mariadb.service.d/mariadb.conf
                conf:
                  Service:
                    NoNewPrivileges: "true"
                    PrivateNetwork: "false"
                    PrivateTmp: "true"
        mariadb_underscore_autoupdate: true

    - name: Include the RabbitMQ role
      ansible.builtin.include_role:
        name: rabbitmq
      vars:  # noqa var-naming[no-role-prefix]
        rabbitmq: true
        rabbitmq_users:
          - username: onlyoffice
            state: present
        rabbitmq_configuration:
          listeners.tcp.local: "{{ ansible_facts.default_ipv4.address }}:5672"
        rabbitmq_systemd_units:
          - name: epmd
            files:
              - path: /etc/systemd/system/epmd.service.d/override.conf
                conf:
                  Service:
                    Environment: 'ERL_EPMD_ADDRESS="{{ ansible_facts.default_ipv4.address }}"'

    - name: Include the Users role
      ansible.builtin.include_role:
        name: users
      vars:  # noqa var-naming[no-role-prefix]
        users_mariadb: true
        users:
          onlyoffice:
            users_state: present
            users_name: ONLYOFFICE
            users_notify_passwd: false
            users_mariadb_notify_passwd: false
            users_mariadb_databases:
              - onlyoffice
            users_home_owner: onlyoffice
            users_home_group: onlyoffice
            users_home_mode: "0750"

    - name: Include the ONLYOFFICE Document Server role
      ansible.builtin.include_role:
        name: onlyoffice
        # tasks_from: apt.yml
      vars:  # noqa var-naming[no-role-prefix]
        onlyoffice: true
        onlyoffice_ds_host: "{{ ansible_facts.default_ipv4.address }}"
        onlyoffice_ds_port: "80"
        onlyoffice_nginx_localhost_domain: "{{ ansible_facts.default_ipv4.address }}"
        onlyoffice_nginx_localhost_port: 82
        onlyoffice_rabbitmq_host: "{{ ansible_facts.default_ipv4.address }}"
        onlyoffice_ssl: false
        onlyoffice_wopi: ignore
...
