# Copyright 2020-2024 Chris Croome
#
# This file is part of the Webarchitects ONLYOFFICE Ansible role.
#
# The Webarchitects ONLYOFFICE Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects ONLYOFFICE Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects ONLYOFFICE Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Verify as root
  become: true
  connection: local
  gather_facts: true
  hosts:
    - localhost
  tasks:

    - name: ONLYOFFICE Document Server present
      ansible.builtin.apt:
        pkg:
          - onlyoffice-documentserver
        install_recommends: true
        state: present
      check_mode: true

    - name: Gather service facts
      ansible.builtin.service_facts:
      register: molecule_service_facts

    - name: Debug service facts
      ansible.builtin.debug:
        var: molecule_service_facts

    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
      register: molecule_port_facts

    - name: Debug listening ports
      ansible.builtin.debug:
        var: molecule_port_facts

    - name: Check Nginx config when the service is listening on port 443
      block:

        - name: Slurp ds.conf is Nginx is listening on 443
          ansible.builtin.slurp:
            src: /etc/onlyoffice/documentserver/nginx/ds.conf
          register: molecule_ds_b64encoded

        - name: Decode the base64 encoded version of the file and set a variable
          ansible.builtin.set_fact:
            molecule_ds_contents: "{{ molecule_ds_b64encoded['content'] | ansible.builtin.b64decode | trim }}"

        - name: Debug molecule_ds_contents
          ansible.builtin.debug:
            var: molecule_ds_contents

      when: molecule_port_facts | community.general.json_query('molecule_port_facts.ansible_facts.tcp_listen[?port==`443`].name') | unique == "nginx"

    - name: ONLYOFFICE healthcheck
      ansible.builtin.uri:
        url: "http://{{ ansible_default_ipv4.address }}/healthcheck"
        return_content: true
      register: molecule_onlyoffice_healthcheck

    - name: Debug ONLYOFFICE healthcheck
      ansible.builtin.debug:
        var: molecule_onlyoffice_healthcheck.content

    - name: Ensure that the ONLYOFFICE healthcheck is true
      ansible.builtin.assert:
        that:
          - molecule_onlyoffice_healthcheck.content == "true"

    - name: ONLYOFFICE info
      ansible.builtin.uri:
        url: "http://{{ ansible_default_ipv4.address }}:82/info/info.json"
        return_content: true
      register: molecule_onlyoffice_info

    - name: Debug ONLYOFFICE info
      ansible.builtin.debug:
        var: molecule_onlyoffice_info.content
...
