# Copyright 2020-2024 Chris Croome
#
# This file is part of the Webarchitects ONLYOFFICE Ansible role.
#
# The Webarchitects ONLYOFFICE Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects ONLYOFFICE Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects ONLYOFFICE Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Verify as root
  become: true
  connection: local
  gather_facts: true
  hosts:
    - localhost
  tasks:

    - name: Verify in a block to allow a rescue
      block:

        - name: ONLYOFFICE Document Server present
          ansible.builtin.apt:
            pkg:
              - onlyoffice-documentserver
            install_recommends: true
            state: present
          check_mode: true

        - name: Restart MariaDB
          ansible.builtin.systemd_service:
            name: mariadb
            state: restarted
          register: molecule_mariadb_restart
          until:
            - molecule_mariadb_restart.status.SubState is defined
            - molecule_mariadb_restart.status.SubState == "running"
            - molecule_mariadb_restart.status.Result is defined
            - molecule_mariadb_restart.status.Result == "success"
          retries: 10
          delay: 3

        - name: Restart RabbitMQ
          ansible.builtin.systemd_service:
            name: rabbitmq-server
            state: restarted
          register: molecule_rabbitmq_restart
          until:
            - molecule_rabbitmq_restart.status.SubState is defined
            - molecule_rabbitmq_restart.status.SubState == "running"
            - molecule_rabbitmq_restart.status.Result is defined
            - molecule_rabbitmq_restart.status.Result == "success"
          retries: 10
          delay: 3

        - name: Restart ONLYOFFICE ds-docservice
          ansible.builtin.systemd_service:
            name: ds-docservice
            state: restarted
          register: molecule_ds_docservice_restart
          until:
            - molecule_ds_docservice_restart.status.SubState is defined
            - molecule_ds_docservice_restart.status.SubState == "running"
            - molecule_ds_docservice_restart.status.Result is defined
            - molecule_ds_docservice_restart.status.Result == "success"
          retries: 10
          delay: 3

        - name: Gather service facts
          ansible.builtin.service_facts:

        - name: Set a fact for the mariadb systemd service
          ansible.builtin.set_fact:
            molecule_mariadb: "{{ ansible_facts.services | community.general.json_query(molecule_mariadb_jpq) }}"
          vars:
            molecule_mariadb_jpq: '["mariadb.service"]|[0]'

        - name: Debug molecule_mariadb
          ansible.builtin.debug:
            var: molecule_mariadb

        - name: MariaDB should be enabled and running
          ansible.builtin.assert:
            that:
              - molecule_mariadb.state == "running"
              - molecule_mariadb.status == "enabled"
            quiet: true

        - name: Set a fact for the rabbitmq-server systemd service
          ansible.builtin.set_fact:
            molecule_rabbitmq: "{{ ansible_facts.services | community.general.json_query(molecule_rabbitmq_jpq) }}"
          vars:
            molecule_rabbitmq_jpq: '["rabbitmq-server.service"]|[0]'

        - name: Debug molecule_rabbitmq
          ansible.builtin.debug:
            var: molecule_rabbitmq

        - name: MariaDB should be enabled and running
          ansible.builtin.assert:
            that:
              - molecule_rabbitmq.state == "running"
              - molecule_rabbitmq.status == "enabled"
            quiet: true

        - name: Set a fact for the ds-docservice systemd service
          ansible.builtin.set_fact:
            molecule_ds_docservice: "{{ ansible_facts.services | community.general.json_query(molecule_ds_docservice_jpq) }}"
          vars:
            molecule_ds_docservice_jpq: '["ds-docservice.service"]|[0]'

        - name: Debug molecule_ds_docservice
          ansible.builtin.debug:
            var: molecule_ds_docservice

        - name: The ONLYOFFICE Document Server should be enabled and running
          ansible.builtin.assert:
            that:
              - molecule_ds_docservice.state == "running"
              - molecule_ds_docservice.status == "enabled"
            quiet: true

        - name: Gather facts on listening ports
          community.general.listen_ports_facts:

        - name: Set a fact for the ports that the mysql user is listening on
          ansible.builtin.set_fact:
            molecule_mariadb_ports: "{{ ansible_facts.tcp_listen | community.general.json_query(molecule_mariadb_ports_jpq) }}"
          vars:
            molecule_mariadb_ports_jpq: "[?user=='mysql']"

        - name: Debug ports that the mysql user is listening on
          ansible.builtin.debug:
            var: molecule_mariadb_ports

        - name: Set a fact for the ports that the epmd user is listening on
          ansible.builtin.set_fact:
            molecule_epmd_ports: "{{ ansible_facts.tcp_listen | community.general.json_query(molecule_epmd_ports_jpq) }}"
          vars:
            molecule_epmd_ports_jpq: "[?user=='ds']"

        - name: Debug ports that the epmd user is listening on
          ansible.builtin.debug:
            var: molecule_epmd_ports

        - name: Set a fact for the ports that the rabbitmq user is listening on
          ansible.builtin.set_fact:
            molecule_rabbitmq_ports: "{{ ansible_facts.tcp_listen | community.general.json_query(molecule_rabbitmq_ports_jpq) }}"
          vars:
            molecule_rabbitmq_ports_jpq: "[?user=='rabbitmq']"

        - name: Debug ports that the rabbitmq user is listening on
          ansible.builtin.debug:
            var: molecule_rabbitmq_ports

        - name: Set a fact for the ports that the ds user is listening on
          ansible.builtin.set_fact:
            molecule_ds_ports: "{{ ansible_facts.tcp_listen | community.general.json_query(molecule_ds_ports_jpq) }}"
          vars:
            molecule_ds_ports_jpq: "[?user=='ds']"

        - name: Debug ports that the ds user is listening on
          ansible.builtin.debug:
            var: molecule_ds_ports

        - name: ONLYOFFICE healthcheck
          ansible.builtin.uri:
            url: "http://{{ ansible_facts.default_ipv4.address }}/healthcheck"
            return_content: true
          register: molecule_onlyoffice_healthcheck
          until:
            - molecule_onlyoffice_healthcheck.content is defined
            - molecule_onlyoffice_healthcheck.content == "true"
          retries: 10
          delay: 5

        - name: ONLYOFFICE info
          ansible.builtin.uri:
            url: "http://{{ ansible_facts.default_ipv4.address }}:82/info/info.json"
            return_content: true
          register: molecule_onlyoffice_info
          until:
            - molecule_onlyoffice_info.json is defined
            - molecule_onlyoffice_info.content | ansible.builtin.type_debug == "dict"
          retries: 10
          delay: 5

        - name: Debug ONLYOFFICE info content ServerInfo content serverInfo
          ansible.builtin.debug:
            var: molecule_onlyoffice_info.json.serverInfo

      rescue:

        - name: Debug ONLYOFFICE healthcheck
          ansible.builtin.debug:
            var: molecule_onlyoffice_healthcheck.content
          when: molecule_onlyoffice_healthcheck.content is defined

        # - name: Debug listening ports
        #   ansible.builtin.debug:
        #     var: ansible_facts.tcp_listen

        - name: Get debconf values for onlyoffice-documentserver
          ansible.builtin.debconf:
            name: onlyoffice-documentserver
          register: molecule_onlyoffice_dcnf

        - name: Debug molecule_onlyoffice_dcnf
          ansible.builtin.debug:
            var: molecule_onlyoffice_dcnf
            verbosity: 2

        - name: Create a list of the existing debconf values
          ansible.builtin.set_fact:
            molecule_onlyoffice_dcnf_current: "{{ molecule_onlyoffice_dcnf.current | ansible.builtin.dict2items }}"
          when:
            - molecule_onlyoffice_dcnf.current is defined
            - molecule_onlyoffice_dcnf.current != {}

        - name: Debug molecule_onlyoffice_dcnf_current
          ansible.builtin.debug:
            var: molecule_onlyoffice_dcnf_current
          when: molecule_onlyoffice_dcnf_current is defined

        - name: Find files in /etc/nginx/sites-enabled
          ansible.builtin.find:
            path: /etc/nginx/sites-enabled
          register: molecule_nginx_sites_enabled

        - name: Debug molecule_nginx_sites_enabled.files
          ansible.builtin.debug:
            var: molecule_nginx_sites_enabled.files

        - name: Slurp /etc/onlyoffice/documentserver/nginx/ds.conf
          ansible.builtin.slurp:
            src: /etc/onlyoffice/documentserver/nginx/ds.conf
          register: molecule_onlyoffice_documentserver_nginx_ds_b64encoded

        - name: Decode the base64 encoded version of /etc/onlyoffice/documentserver/nginx/ds.conf and set a fact
          ansible.builtin.set_fact:
            molecule_onlyoffice_documentserver_nginx_ds: >-
             {{ molecule_onlyoffice_documentserver_nginx_ds_b64encoded['content'] |
             ansible.builtin.b64decode | trim }}

        - name: Debug the contents of /etc/onlyoffice/documentserver/nginx/ds.conf
          ansible.builtin.debug:
            var: molecule_onlyoffice_documentserver_nginx_ds

        - name: Slurp /etc/onlyoffice/documentserver/nginx/includes/http-common.conf
          ansible.builtin.slurp:
            src: /etc/onlyoffice/documentserver/nginx/includes/http-common.conf
          register: molecule_onlyoffice_documentserver_nginx_http_common_b64encoded

        - name: Decode the base64 encoded version of /etc/onlyoffice/documentserver/nginx/includes/http-common.conf and set a fact
          ansible.builtin.set_fact:
            molecule_onlyoffice_documentserver_nginx_http_common: >-
             {{ molecule_onlyoffice_documentserver_nginx_http_common_b64encoded['content'] |
             ansible.builtin.b64decode | trim }}

        - name: Debug the contents of /etc/onlyoffice/documentserver/nginx/includes/http-common.conf
          ansible.builtin.debug:
            var: molecule_onlyoffice_documentserver_nginx_http_common

        - name: "Check the response from {{ molecule_healthcheck_url }}"
          ansible.builtin.uri:
            url: "{{ molecule_healthcheck_url }}"
            method: GET
          check_mode: false
          vars:
            molecule_healthcheck_url: "http://{{ ansible_facts.default_ipv4.address }}:8000/healthcheck"
          changed_when: false
          failed_when: false
          register: molecule_onlyoffice_healthcheck

        - name: Debug molecule_onlyoffice_healthcheck
          ansible.builtin.debug:
            var: molecule_onlyoffice_healthcheck

        - name: Find .log files in /var/log/onlyoffice/documentserver
          ansible.builtin.find:
            path: /var/log/onlyoffice/documentserver/
            pattern: "*.log"
            recurse: true
          register: molecule_onlyoffice_documentserver_logs

        - name: Slurp and print the ONLYOFFICE log files
          block:

            - name: Slurp the log files
              ansible.builtin.slurp:
                src: "{{ molecule_onlyoffice_documentserver_log_path }}"
              loop: "{{ molecule_onlyoffice_documentserver_logs.files | community.general.json_query('[].path') }}"
              loop_control:
                loop_var: molecule_onlyoffice_documentserver_log_path
              register: molecule_onlyoffice_documentserver_log_files_b64encoded

            - name: Decode the base64 encoded log files
              ansible.builtin.set_fact:
                molecule_onlyoffice_documentserver_log_files_content: >-
                  {{ molecule_onlyoffice_documentserver_log_files_b64encoded |
                  community.general.json_query('results[].content') |
                  map('ansible.builtin.b64decode') }}

            - name: Debug the slurped log file contents
              ansible.builtin.debug:
                var: molecule_onlyoffice_documentserver_log_files_content

          when: molecule_onlyoffice_documentserver_logs.files | community.general.json_query('[].path') != []

        - name: Fail
          ansible.builtin.fail:
...
