# Copyright 2020-2024 Chris Croome
#
# This file is part of the Webarchitects ONLYOFFICE Ansible role.
#
# The Webarchitects ONLYOFFICE Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects ONLYOFFICE Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects ONLYOFFICE Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Verify as root
  become: true
  connection: local
  gather_facts: true
  hosts:
    - localhost
  tasks:

    - name: ONLYOFFICE Document Server present
      ansible.builtin.apt:
        pkg:
          - onlyoffice-documentserver
        install_recommends: true
        state: present
      check_mode: true

    - name: Gather service facts
      ansible.builtin.service_facts:
      register: molecule_service_facts

    - name: Debug service facts
      ansible.builtin.debug:
        var: molecule_service_facts

    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
      register: molecule_port_facts

    - name: Debug listening ports
      ansible.builtin.debug:
        var: molecule_port_facts

    - name: ONLYOFFICE healthcheck
      block:

        - name: ONLYOFFICE healthcheck
          ansible.builtin.uri:
            url: "http://{{ ansible_facts.default_ipv4.address }}/healthcheck"
            return_content: true
          register: molecule_onlyoffice_healthcheck
          until:
            - molecule_onlyoffice_healthcheck.content is defined
            - molecule_onlyoffice_healthcheck.content == "true"
          retries: 10
          delay: 5

      rescue:

        - name: Debug ONLYOFFICE healthcheck
          ansible.builtin.debug:
            var: molecule_onlyoffice_healthcheck.content

        - name: Find files in /etc/nginx/sites-enabled
          ansible.builtin.find:
            path: /etc/nginx/sites-enabled
          register: molecule_nginx_sites_enabled

        - name: Debug molecule_nginx_sites_enabled.files
          ansible.builtin.debug:
            var: molecule_nginx_sites_enabled.files

        - name: Find .conf files in /etc/onlyoffice/documentserver/nginx/
          ansible.builtin.find:
            path: /etc/onlyoffice/documentserver/nginx/
            pattern: "*.conf"
          register: molecule_onlyoffice_documentserver_nginx

        - name: Debug molecule_onlyoffice_documentserver_nginx.files
          ansible.builtin.debug:
            var: molecule_onlyoffice_documentserver_nginx.files

    - name: ONLYOFFICE info
      ansible.builtin.uri:
        url: "http://{{ ansible_facts.default_ipv4.address }}:82/info/info.json"
        return_content: true
      register: molecule_onlyoffice_info

    - name: Debug ONLYOFFICE info
      ansible.builtin.debug:
        var: molecule_onlyoffice_info.content
...
