---
users:
  root:
    users_state: present
    users_home: /root
    users_editor: vim
    users_email: chris@webarchitects.co.uk
    users_home_mode: "0700"
  chris:
    users_state: present
    users_name: Chris Croome
    users_email: chris@webarchitects.co.uk
    users_ssh_public_keys:
      - https://git.coop/chris.keys
    users_groups:
      - sudo
    users_editor: vim
    users_home_mode: "0750"
...
